type Name {
    first: String!
    middle: String
    last: String
}

type User @key(fields: "id") {
    id: ID!
    username: String!
    name: Name!
}

type Query {
    user: User
}

schema {
    query: Query
}