type PingResponse {
    result: String @cache(maxAge: 30, policy: PRIVATE)
    health: String @cache(maxAge: 30)
    user: User
}

extend type User @key(fields: "id") {
  id: ID! @external
  greeting: String
}

type Query {
    ping: PingResponse
}

schema {
    query: Query
}