type PingResponse {
    result: String @cacheControl(maxAge: 10)
    health: String @cacheControl(maxAge: 30)
}

type Query {
    ping: PingResponse @hasRole(oneOf: ["customer"])
}

schema {
    query: Query
}